### ISSUE TITLE
OVERRUN Error

### ISSUE THREAD

**Issue by N7JYS** [F4HTB/Universal_HamRadio_Remote_HTML5#17]
After starting UHRR and watching in run in terminal, I issue a command from the web interface to select a new frequency and SSB mode, this is what I observe,

setFreq:0050000000
Send to all: getFreq 5000000
setMode:AM
overrun

Also its taking 12 seconds after sending this command for the web interface to react. And audio is dropping out.

Noticed on a request to connect to webserver  tornado.general gives an SSL error (SSL: sslv3_ale)

Eric

**Comment by N7JYS** [comment]
I have notice the same issue even after the updates to UHRR and console.js files. The changes that were made did not fix the overrun issue and the 12 seconds of no audio while changing modes. Also LSB mode sets Upper Side Band on my FT-891.

Other wise that program is a blast and almost there. Thanks

Eric

**Comment by F4HTB** [comment]
this error appears when the sound card does not give enough chuncks.
