### ISSUE TITLE
function takes at most 5 arguments (7 given)

### ISSUE THREAD

**Issue by parlotto** [F4HTB/Universal_HamRadio_Remote_HTML5#2]
Hello,
On a pc runing ubuntu 20.04, I have this error when trying to configure :

 http server started
SERVER port 8888
AUDIO outputdevice plughw:CARD=U0x41e0x30d3,DEV=0
AUDIO inputdevice plughw:CARD=U0x41e0x30d3,DEV=0
HAMLIB rig_pathname /dev/ttyUSB2
HAMLIB rig_model TS590S
HAMLIB rig_rate 38400
HAMLIB trxautopower True
**(<class 'TypeError'>, TypeError('function takes at most 5 arguments (7 given)'), <traceback object at 0x7f7e7bde5540>)**

Maybe a problem with the version of hamlib ?
Thanks for this promising software.
Phil.

**Comment by F4HTB** [comment]
Can you get more informations please?
Maybe the screen output?

Thanks

**Comment by parlotto** [comment]
Bonjour, 
Mon indicatif est F5OWL. 
Merci pour ce soft. 

Voici ce que j'obtiens au lancement : 
philippe@jupiter:~/Universal_HamRadio_Remote_HTML5$ ./UHRR 
(<class 'TypeError'>, TypeError('function takes at most 5 arguments (7 given)'), <traceback object at 0x7f19332679c0>) 
http server started 
SERVER port 8888 
AUDIO outputdevice plughw:CARD=U0x41e0x30d3,DEV=0 
AUDIO inputdevice plughw:CARD=U0x41e0x30d3,DEV=0 
HAMLIB rig_pathname /dev/ttyUSB2 
HAMLIB rig_model TS590S 
HAMLIB rig_rate 38400 
HAMLIB trxautopower True 

j'accède par https://127.0.0.1:8888 
Ensuite quand je fais : "Save and Restart server" 

philippe@jupiter:~/Universal_HamRadio_Remote_HTML5$ (<class 'TypeError'>, TypeError('function takes at most 5 arguments (7 given)'), <traceback object at 0x7f05f234db80>) 
http server started 
SERVER port 8888 
AUDIO outputdevice plughw:CARD=U0x41e0x30d3,DEV=0 
AUDIO inputdevice plughw:CARD=U0x41e0x30d3,DEV=0 
HAMLIB rig_pathname /dev/ttyUSB2 
HAMLIB rig_model TS590S 
HAMLIB rig_rate 38400 
HAMLIB trxautopower True 
(<class 'TypeError'>, TypeError('function takes at most 5 arguments (7 given)'), <traceback object at 0x7fc11c7fb840>) 
http server started 

J'ai installé le soft sur ubuntu 20.04. 
J'utilise hamlib 3.3 issue des paquets de la distribution ubuntu 20.04. 
Le navigateur est firefox 82.0. 
En pj mon fichier de conf. 
En espèrant que ce soit utile. 
73 
Philippe 



De: "Olivier SCHMITT" <notifications@github.com> 
À: "F4HTB/Universal_HamRadio_Remote_HTML5" <Universal_HamRadio_Remote_HTML5@noreply.github.com> 
Cc: "philippe arlotto" <arlotto@univ-tln.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 28 Octobre 2020 14:31:43 
Objet: Re: [F4HTB/Universal_HamRadio_Remote_HTML5] function takes at most 5 arguments (7 given) (#2) 






Can you get more informations please? 
Maybe the screen output? 

Thanks

**Comment by F4HTB** [comment]
use raspberry pi instead.
I cannot transpose the code to the stable sources in ubuntu and raspiOS on the same git repo.

**Comment by madpsy** [comment]
Caused by old version of pyalsaaudio. You probably have v0.8.x installed, you need 0.9.0.

`pip3 install --user pyalsaaudio==0.9.0`
