### ISSUE TITLE
Configured serial speed ignored

### ISSUE THREAD

**Issue by iw2nke** [F4HTB/Universal_HamRadio_Remote_HTML5#25]
I am running UHRR on a RPi3 to connect a Kenwood TS-2000.
Unfortunately it is not working as expected.
One of possible root cause seems to be the incorrect serial speed.

With te command  `rigctl -m 2014 -s 19200 -r /dev/ttyAMA0 --set-conf=data_bits=8,stop_bits=1 -vvv f`
the output is:
**Opened rig model 2014, 'TS-2000'
14070000**

The conf file **UHRR.conf** contains the right value
[HAMLIB]
rig_pathname = /dev/ttyAMA0
retry = 5
rig_model = TS2000
trxautopower = False
**rig_rate = 19200**
data_bits = 8
stop_bits = 1

Enabling the `Hamlib.rig_set_debug(Hamlib.RIG_DEBUG_TRACE)` option on the main code of UHRR file, the output is:

rig_open called
port_open called
serial_open called
serial_setup called
serial_setup: tcgetattr
serial_setup: cfmakeraw
**serial_setup: cfsetispeed=57600,0x1001
serial_setup: cfsetospeed=57600,0x1001**
serial_setup: data_bits=8
serial_setup: parity=0
serial_setup: tcsetattr TCSANOW
serial_flush called
tcflush
kenwood_open called
kenwood_get_id called
kenwood_transaction called
kenwood_transaction: cmdstr = ID
rig_flush: called for serial device
serial_flush called
tcflush
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called, rxmax=128
read_string(): Timed out 0.200280 seconds after 0 chars
kenwood_transaction: read_string(len=0)=''
kenwood_transaction: read_string retval < 0, retval = -5, retry_read=0, rs->rigport.retry=0
kenwood_transaction: returning retval=-5
kenwood_open: no response to get_id from rig...continuing anyways.

And obviously the communication fails.

**Comment by F4HTB** [comment]
Thank you for your corrections.
