### ISSUE TITLE
Update the repo

### ISSUE THREAD

**Issue by pepassaco** [F4HTB/Universal_HamRadio_Remote_HTML5#42]
Hi!

The installing instructions as they are now do not work (it gives error in the very last step when installing this repo). This is what I had to do to fix it:

1. In order to fix the error `python3: undefined symbol: opus_strerror`, I installed the opus-tool package by doing `sudo apt-get install opus-tools`
2. In order to fix the `ModuleNotFoundError: No module named 'Hamlib'` error, I changed:

```
PYTHONPATH=/usr/local/lib/python3.7/site-packages:$PYTHONPATH ./UHRR
```

To:

```
PYTHONPATH=/usr/local/lib/python3.9/site-packages:$PYTHONPATH ./UHRR
```

**Comment by F4HTB** [comment]
Many thanks.
I have not tested your fixes but it seems that can be work.
I have add your comment to the installation page.
https://github.com/F4HTB/Universal_HamRadio_Remote_HTML5/wiki/Note-installations,-tests-etc...-(orange-pi-zero,-python-3.....)
