### ISSUE TITLE
hamlib_port_parm_serial error when run the server

### ISSUE THREAD

**Issue by lcyepiz** [F4HTB/Universal_HamRadio_Remote_HTML5#44]
recording...
(<class 'AttributeError'>, AttributeError("module 'hamlib' has no attribute 'hamlib_port_parm_serial'"), <traceback object at 0x74709668>)
HTTP server started.

Any idea?

thanks
73
XE2W

**Comment by lcyepiz** [comment]
i try this:
 PYTHONPATH=/usr/local/lib/python3.11/site-packages:$PYTHONPATH ./UHRR 
now run ok!
thank a lot

**Comment by F4HTB** [comment]
Thank to you
