### ISSUE TITLE
User can create duplicate frequencies in personal frequencies drop-down menu

### ISSUE THREAD

**Issue by dslotter** [F4HTB/Universal_HamRadio_Remote_HTML5#8]
See attached screen capture which shows the defect. Frequency settings should only be stored once.

![Multiple Duplicate Frequencies Bug](https://user-images.githubusercontent.com/6873871/98190427-febb5a00-1ee4-11eb-9a08-30305a143e15.png)

**Comment by F4HTB** [comment]
Thanks for the report.
I will correct the but on the next update.

**Comment by F4HTB** [comment]
This has just been corrected.
